import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from 'next/headers'; 
import "./globals.css";
// 🚨 ADJUST THE IMPORT PATH FOR YOUR PROJECT:
import LogoutButton from './ui/LogoutButton'; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KHIAR HESABDDAR",
  description: "Generated by create MrKazhe",
  icons: {
    icon: '/cu.png',
    shortcut: '/cu.png',
    apple: '/cu.png',
    other: [
      {
        rel: 'apple-touch-icon',
        url: '/cu.png',
      },
    ],
  },
};

const SESSION_TOKEN_NAME = 'app_session'; 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  let username: string | null = null;
  
  const sessionCookie = cookies().get(SESSION_TOKEN_NAME);

  if (sessionCookie) {
    try {
      const sessionData = JSON.parse(sessionCookie.value);
      if (sessionData && sessionData.username) {
          username = sessionData.username; 
      }
    } catch (e) {
      console.error("Failed to parse session cookie:", e);
    }
  }

  const isAuthenticated = !!username; 

  return (
    <html lang="en" dir="rtl">
      <head>
        <link rel="icon" href="/cu.png" type="image/png" sizes="32x32" />
        <link rel="apple-touch-icon" href="/cu.png" />
        <link 
          rel="stylesheet" 
          href="https://fonts.googleapis.com/css2?family=Lalezar&display=swap" 
        />
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header 
          style={{ 
            padding: '15px 30px', 
            backgroundColor: '#343a40', 
            color: 'white', 
            display: 'flex', 
            // 🟢 FIX 1: Set justify-content to space-between
            justifyContent: 'space-between', 
            alignItems: 'center' 
          }}
        >
          {/* LEFT: Title */}
          <h1 style={{margin: 0, flexShrink: 0}}>🥒 حسابدار من</h1>
          
          {/* CENTER: Username (Visible only when authenticated) */}
          <div style={{ flexGrow: 1, textAlign: 'center' }}>
            {isAuthenticated && (
              <span style={{ fontSize: '18px', fontWeight: 'bold', color: '#ffc107' }}>
                👋 {username} 
              </span>
            )}
          </div>
          
          {/* RIGHT: Logout Button (Visible only when authenticated) */}
          <nav style={{ flexShrink: 0 }}>
            {isAuthenticated && <LogoutButton />} 
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}