import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KHIAR HESABDDAR",
  description: "Generated by create MrKazhe",
  icons: {
    icon: '/cu.png', // 👈 Point to your new icon file
    shortcut: '/cu.png',
    apple: '/cu.png',
    other: [
      {
        rel: 'apple-touch-icon',
        url: '/cu.png',
      },
    ],
  },

};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" dir="rtl">
      <head>
        <link rel="icon" href="/cu.png" type="image/png" sizes="32x32" />
        <link rel="apple-touch-icon" href="/cu.png" />
        {/* --- NEW SAFE FONT LINK ADDED HERE (Lalezar from Google Fonts) --- */}
        <link 
          rel="stylesheet" 
          href="https://fonts.googleapis.com/css2?family=Lalezar&display=swap" 
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
